name: Ultra E2E Testing

on:
  pull_request:
    branches: ['main']

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Step 1 Pull Secrets
        run: |
          echo "STANDARD_USER_PASSWORD=${{ secrets.STANDARD_USER_PASSWORD }}" >> $GITHUB_ENV

      - name: Step 2 Install dependencies
        run: |
          npm install
          npm install -g chromedriver

      - name: Step 3 Run tests
        run: npm run wdio:test:desktop
        env:
          BROWSER: ChromeFireFox
          HEADLESS: Yes

      - name: Step 4 Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Step 5 Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Step 6 Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
